<?php

namespace app\admin\controller;

use think\Controller;

use think\Db;
use think\Loader;
use think\Request;

class Base extends Controller
{
    public function _initialize()
    {
        if (!session('username')){
            $this->redirect("/uset/public/admin/login/index");
        }
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 显示资源列表
     *
     * @return \think\Response
     */
    public function index()
    {
        $res=Db::table('info')->find();
        $this->assign("data",$res);
        //1.查询数据；渲染页面
        return view("index");
    }

    /**
     * 显示创建资源表单页.
     *
     * @return \think\Response
     */
    public function upload()
    {
        $file=\request()->file('file');
        $info=$file->move(ROOT_PATH . 'public' . DS . 'uploads');
        if($info){
            // 输出 20160820/42a79759f284b767dfcb2a0197904287.jpg
//            var_dump($info);
              $data=[
                  'code'=>200,
                  'msg'=>"图片上传成功",
                  'url'=>'/uset/public/uploads/'.$info->getSaveName()
              ];
        }else{
            // 上传失败获取错误信息
            $data=[
                'code'=>404,
                'msg'=>"图片上传失败",
                'url'=>$file->getError()
            ];
          }
        return $data;
    }

    //富文本图片上传
    public function load()
    {
        $file=\request()->file('file');
        $info=$file->move(ROOT_PATH . 'public' . DS . 'uploads');
        if($info){
            $data=[
                'code'=>0,
                'msg'=>"图片上传成功",
                'data'=>[
                    'src'=>'/uset/public/uploads/'.$info->getSaveName(),
                ]
            ];
        }else{
            // 上传失败获取错误信息
            $data=[
                'code'=>404,
                'msg'=>"图片上传失败",
                'url'=>$file->getError()
            ];
        }
        return $data;
    }
    /**
     * 保存新建的资源
     *
     * @param  \think\Request  $request
     * @return \think\Response
     */
    public function query(){
        $requst=\request();
        $data=$requst->post();
        unset($data['file']);
        if (!empty($data['src'])){
            $src='../'.substr($data['src'],6);
            unlink($src);
        }
        unset($data['src']);
        $res=Db::table('info')->where('id',$data['id'])
            ->update(['title'=>$data['title'],'keywords'=>$data['keywords'],'desc'=>$data['desc'],'logo'=>$data['logo'],'phone'=>$data['phone'],'email'=>$data['email'],'address'=>$data['address'],'copyright'=>$data['copyright'],'id'=>$data['id']]);
        if ($res){
            $data=[
                'code'=>200,
                'msg'=>"修改成功"
            ];
        }else{
            $data=[
                'code'=>404,
                'msg'=>"修改失败"
            ];
        }
        return $data;
    }
}
